import charactersReducer, {
  setActiveCharacter,
  clearCharacters,
  clearError,
} from '@store/slices/charactersSlice';
import type { Character, CharacterSummary } from '@/types';
import { Size, Alignment, BonusType, EncumbranceVariant } from '@/types';

const mockCharacterSummary: CharacterSummary = {
  id: 'char-1',
  name: 'Thorin',
  level: 5,
  race: 'Dwarf',
  classes: 'Fighter 5',
  lastUpdated: new Date('2025-06-01'),
};

// Minimal Character for testing reducer logic
const mockCharacter: Character = {
  info: {
    id: 'char-1',
    name: 'Thorin',
    player: 'Mark',
    userId: 'user-123',
    race: {
      name: 'Dwarf',
      sizeMod: Size.Medium,
      baseSpeed: 20,
      alternativeMovements: {},
      abilityModifiers: { con: 2, wis: 2, cha: -2 },
      traits: [],
      languages: ['Common', 'Dwarven'],
      bonusLanguages: [],
    },
    size: Size.Medium,
    alignment: Alignment.LawfulGood,
    deity: 'Torag',
    gender: 'Male',
    age: 85,
    height: '4\'2"',
    weight: '180 lbs',
    hair: 'Black',
    eyes: 'Brown',
    skin: 'Tan',
    homeland: 'Janderhoff',
    campaign: '',
    portrait: '',
    background: '',
    notes: '',
  },
  abilityScores: {
    str: {
      base: 16,
      racial: 0,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 16,
      modifier: 3,
      tempTotal: 16,
      tempModifier: 3,
    },
    dex: {
      base: 12,
      racial: 0,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 12,
      modifier: 1,
      tempTotal: 12,
      tempModifier: 1,
    },
    con: {
      base: 14,
      racial: 2,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 16,
      modifier: 3,
      tempTotal: 16,
      tempModifier: 3,
    },
    int: {
      base: 10,
      racial: 0,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 10,
      modifier: 0,
      tempTotal: 10,
      tempModifier: 0,
    },
    wis: {
      base: 12,
      racial: 2,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 14,
      modifier: 2,
      tempTotal: 14,
      tempModifier: 2,
    },
    cha: {
      base: 10,
      racial: -2,
      inherent: 0,
      damage: 0,
      drain: 0,
      bonuses: {
        enhancement: [],
        morale: [],
        size: [],
        alchemical: [],
        insight: [],
        profane: [],
        sacred: [],
        luck: [],
        circumstance: [],
        competence: [],
        untyped: [],
      },
      total: 8,
      modifier: -1,
      tempTotal: 8,
      tempModifier: -1,
    },
  },
  classes: {
    classes: [
      {
        name: 'Fighter',
        level: 5,
        hitDieSize: 10,
        hitDieResults: [10, 7, 8, 6, 9],
        skillRanks: 2,
        classSkills: ['Climb', 'Intimidate', 'Swim'],
        babProgression: 'Full' as never,
        fortProgression: 'Good' as never,
        refProgression: 'Poor' as never,
        willProgression: 'Poor' as never,
        classFeatures: [],
      },
    ],
    totalLevel: 5,
    baseAttackBonus: [5],
    baseFortSave: 4,
    baseRefSave: 1,
    baseWillSave: 1,
    favoredClassBonuses: [],
  },
  combatStats: {
    hitPoints: {
      base: 40,
      constitution: 15,
      favoredClass: 5,
      other: 0,
      current: 60,
      temporary: 0,
      nonlethal: 0,
    },
    armorClass: {
      base: 10,
      armor: 0,
      shield: 0,
      dexterity: 1,
      size: 0,
      natural: 0,
      deflection: 0,
      dodge: 0,
      misc: 0,
      total: 11,
      touch: 11,
      flatFooted: 10,
    },
    combatManeuver: {
      bonus: { baseAttack: 5, strengthMod: 3, sizeMod: 0, miscMods: [], total: 8 },
      defense: {
        baseValue: 10,
        baseAttack: 5,
        strengthMod: 3,
        dexterityMod: 1,
        sizeMod: 0,
        armorBonus: 0,
        shieldBonus: 0,
        naturalArmorBonus: 0,
        deflectionBonus: 0,
        dodgeBonus: 0,
        miscMods: [],
        total: 19,
        flatFooted: 18,
      },
    },
    initiative: { dexterity: 1, misc: 0, total: 1 },
    savingThrows: {
      fortitude: { base: 4, ability: 3, magic: 0, misc: 0, temporary: 0, total: 7 },
      reflex: { base: 1, ability: 1, magic: 0, misc: 0, temporary: 0, total: 2 },
      will: { base: 1, ability: 2, magic: 0, misc: 0, temporary: 0, total: 3 },
    },
    movement: { base: 20, armor: 0, fly: 0, swim: 0, climb: 0, burrow: 0, current: 20 },
    attackBonuses: {
      baseAttack: [5],
      strengthMod: 3,
      sizeMod: 0,
      abilityModifiers: { melee: 'STR', ranged: 'DEX', thrown: 'STR' },
      miscMods: { melee: [], ranged: [], thrown: [], all: [] },
      meleeTotal: 8,
      rangedTotal: 6,
      allAttacks: { melee: [8], ranged: [6] },
    },
  },
  skills: {
    acrobatics: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    appraise: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    bluff: {
      isClassSkill: false,
      ranks: 0,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: -1,
    },
    climb: {
      isClassSkill: true,
      ranks: 5,
      ability: 'STR',
      abilityMod: 3,
      classSkillBonus: 3,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 11,
    },
    craft: [],
    diplomacy: {
      isClassSkill: false,
      ranks: 0,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: -1,
    },
    disableDevice: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    disguise: {
      isClassSkill: false,
      ranks: 0,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: -1,
    },
    escapeArtist: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    fly: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    handleAnimal: {
      isClassSkill: true,
      ranks: 0,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: -1,
    },
    heal: {
      isClassSkill: false,
      ranks: 0,
      ability: 'WIS',
      abilityMod: 2,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 2,
    },
    intimidate: {
      isClassSkill: true,
      ranks: 3,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 3,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 5,
    },
    knowledgeArcana: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeDungeoneering: {
      isClassSkill: true,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeEngineering: {
      isClassSkill: true,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeGeography: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeHistory: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeLocal: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeNature: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeNobility: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgePlanes: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    knowledgeReligion: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    linguistics: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    perception: {
      isClassSkill: false,
      ranks: 0,
      ability: 'WIS',
      abilityMod: 2,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 2,
    },
    perform: [],
    profession: [],
    ride: {
      isClassSkill: true,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    senseMotive: {
      isClassSkill: false,
      ranks: 0,
      ability: 'WIS',
      abilityMod: 2,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 2,
    },
    sleightOfHand: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    spellcraft: {
      isClassSkill: false,
      ranks: 0,
      ability: 'INT',
      abilityMod: 0,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 0,
    },
    stealth: {
      isClassSkill: false,
      ranks: 0,
      ability: 'DEX',
      abilityMod: 1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 1,
    },
    survival: {
      isClassSkill: true,
      ranks: 2,
      ability: 'WIS',
      abilityMod: 2,
      classSkillBonus: 3,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 7,
    },
    swim: {
      isClassSkill: true,
      ranks: 0,
      ability: 'STR',
      abilityMod: 3,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: 3,
    },
    useMagicDevice: {
      isClassSkill: false,
      ranks: 0,
      ability: 'CHA',
      abilityMod: -1,
      classSkillBonus: 0,
      racial: 0,
      trait: 0,
      item: 0,
      misc: 0,
      armorPenalty: 0,
      total: -1,
    },
    totalRanks: 10,
  },
  feats: { feats: [], totalFeats: 0, bonusFeats: 0 },
  traits: { traits: [] },
  equipment: {
    weapons: [],
    armor: [],
    shields: [],
    magicItems: [],
    gear: [],
    equippedSlots: new Map(),
    encumbranceSettings: { enabled: false, variant: EncumbranceVariant.CORE_RULES },
    totalWeight: 0,
    lightLoad: 76,
    mediumLoad: 153,
    heavyLoad: 230,
    currentLoad: 'Light',
    acPenalty: 0,
    maxDexBonus: 99,
    spellFailure: 0,
  },
  spellcasting: { spellcastingClasses: [], preparedSpells: [], knownSpells: [], spellbooks: [] },
  specialAbilities: { specialAbilities: [] },
  conditions: { activeConditions: [] },
  experience: { current: 15000, nextLevel: 23000 },
  currency: { platinum: 0, gold: 150, silver: 30, copper: 0, totalGP: 153 },
  buffs: [],
  savedBuffs: [],
  schemaVersion: '1.1.0',
  lastUpdated: new Date('2025-06-01'),
};

describe('charactersSlice', () => {
  const initialState = {
    characters: [] as CharacterSummary[],
    activeCharacter: null as Character | null,
    loading: false,
    error: null as string | null,
  };

  it('should return the initial state', () => {
    expect(charactersReducer(undefined, { type: 'unknown' })).toEqual(initialState);
  });

  describe('setActiveCharacter', () => {
    it('should set active character', () => {
      const state = charactersReducer(initialState, setActiveCharacter(mockCharacter));
      expect(state.activeCharacter).toEqual(mockCharacter);
    });

    it('should clear active character', () => {
      const stateWithCharacter = { ...initialState, activeCharacter: mockCharacter };
      const state = charactersReducer(stateWithCharacter, setActiveCharacter(null));
      expect(state.activeCharacter).toBeNull();
    });
  });

  describe('clearCharacters', () => {
    it('should clear all characters and active character', () => {
      const stateWithData = {
        ...initialState,
        characters: [mockCharacterSummary],
        activeCharacter: mockCharacter,
      };
      const state = charactersReducer(stateWithData, clearCharacters());
      expect(state.characters).toHaveLength(0);
      expect(state.activeCharacter).toBeNull();
    });
  });

  describe('clearError', () => {
    it('should clear the error', () => {
      const errorState = { ...initialState, error: 'Something failed' };
      const state = charactersReducer(errorState, clearError());
      expect(state.error).toBeNull();
    });
  });

  describe('async thunk reducers', () => {
    // fetchCharacters
    it('should set loading on fetchCharacters pending', () => {
      const state = charactersReducer(initialState, { type: 'characters/fetchCharacters/pending' });
      expect(state.loading).toBe(true);
      expect(state.error).toBeNull();
    });

    it('should set characters on fetchCharacters fulfilled', () => {
      const loadingState = { ...initialState, loading: true };
      const state = charactersReducer(loadingState, {
        type: 'characters/fetchCharacters/fulfilled',
        payload: [mockCharacterSummary],
      });
      expect(state.loading).toBe(false);
      expect(state.characters).toEqual([mockCharacterSummary]);
    });

    it('should set error on fetchCharacters rejected', () => {
      const loadingState = { ...initialState, loading: true };
      const state = charactersReducer(loadingState, {
        type: 'characters/fetchCharacters/rejected',
        payload: 'Network error',
      });
      expect(state.loading).toBe(false);
      expect(state.error).toBe('Network error');
    });

    // fetchCharacter
    it('should set active character on fetchCharacter fulfilled', () => {
      const loadingState = { ...initialState, loading: true };
      const state = charactersReducer(loadingState, {
        type: 'characters/fetchCharacter/fulfilled',
        payload: mockCharacter,
      });
      expect(state.loading).toBe(false);
      expect(state.activeCharacter).toEqual(mockCharacter);
    });

    // deleteCharacter
    it('should remove character from list on deleteCharacter fulfilled', () => {
      const stateWithCharacters = {
        ...initialState,
        characters: [mockCharacterSummary],
        activeCharacter: mockCharacter,
        loading: true,
      };
      const state = charactersReducer(stateWithCharacters, {
        type: 'characters/deleteCharacter/fulfilled',
        meta: { arg: 'char-1' },
      });
      expect(state.loading).toBe(false);
      expect(state.characters).toHaveLength(0);
      expect(state.activeCharacter).toBeNull();
    });

    it('should not clear active character if deleting a different character', () => {
      const stateWithCharacters = {
        ...initialState,
        characters: [
          mockCharacterSummary,
          { ...mockCharacterSummary, id: 'char-2', name: 'Elara' },
        ],
        activeCharacter: mockCharacter,
        loading: true,
      };
      const state = charactersReducer(stateWithCharacters, {
        type: 'characters/deleteCharacter/fulfilled',
        meta: { arg: 'char-2' },
      });
      expect(state.characters).toHaveLength(1);
      expect(state.activeCharacter).toEqual(mockCharacter);
    });
  });
});
